music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'



urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
    url(r'^travel/$', views.travel, name='travel'),
    url(r'^software/$', views.software, name='software'),
    url(r'^mind/$', views.mind, name='mind'),

]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
import datetime
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone

class Album(models.Model):

    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=600)
    genre = models.CharField(max_length=100)
    call_to_action=models.CharField(max_length=150, default='')
    album_logo = models.FileField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django import forms
from django.contrib.auth.models import User

# from .models import Album, Song


# class AlbumForm(forms.ModelForm):
#
#     class Meta:
#         model = Album
#         fields = ['artist', 'album_title', 'genre', 'album_logo']
#
#
# class SongForm(forms.ModelForm):
#
#     class Meta:
#         model = Song
#         fields = ['song_title', 'audio_file']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View
from django.db.models import Q
from .models import Album, Song
from .forms import UserForm





def index(request):
    all_albums=Album.objects.order_by('-pub_date')

    # all_albums.order_by('-pub_date')
    return render(request, 'music/index.html', {'all_albums':all_albums})

# class IndexView(generic.ListView):
#     template_name = 'music/index.html'
#     context_object_name = 'all_albums'
#     def get_queryset(self):
#         return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields=['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields=['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class =UserForm
    template_name = 'music/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})


    #process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            #cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.if_active:
                    login(request, user)
                    return redirect('music:index')
        return render(request, self.template_name, {'form': form})


def travel(request):
    all_albums = Album.objects.filter(genre="Rock")

    # all_albums.order_by('-pub_date')
    return render(request, 'music/travel.html', {'all_albums': all_albums})


def software(request):
    all_albums = Album.objects.filter(genre="Jazz")

    # all_albums.order_by('-pub_date')
    return render(request, 'music/travel.html', {'all_albums': all_albums})


def mind(request):
    all_albums = Album.objects.filter(genre="Modern")

    # all_albums.order_by('-pub_date')
    return render(request, 'music/travel.html', {'all_albums': all_albums})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Album</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Neyo{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Bungee">
    <link rel="stylesheet" type="text/css" href="{% static 'music/styled.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">

    <script src="{% static 'music/js/main.js' %}"></script>

</head>
<body>

{#<nav class="navbar navbar-inverse navbar-static-top">#}
<div class="container-fluid">
<div class="row">
    <div class="col-md-12">
        <img src="/media/neyologo.png" href="{% url 'music:index' %}">
    </div>
</div>


{##}

{#        <!--Header -->#}
{#    <div>#}
{##}
{#   <div class="wrapper header-wrapper">#}
{#    <div class="header grid">#}
{#      <div class="wrapper date-social-wrapper">#}
{#        <div class="date-nav full">#}
{#        </div>#}
{#        <div class="social-nav">#}
{#          <ul class="nav">#}
{#          </ul>#}
{#        </div>#}
{#      </div>#}
{#      <a class="logo" href="{% url 'music:index' %}">#}
{##}
{#        <img src="/media/neyologo.png">#}
{##}
{#      </a>#}
{##}
{##}
{##}
{#    </div>#}
{#  </div>#}
{##}
{#        </div>#}

        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
{#            <a class="navbar-brand" href="{% url 'music:index' %}">NEYO</a>#}

        </div>
         <!-- Items -->
        <div class="collapse navbar-collapse " id="topNavBar">


            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'music:mind' %}"> Mind</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'music:travel' %}">&nbsp; Travel</a></li>
                <li>
                    <a href="{% url 'music:software' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Software
                    </a>
                </li>
                <li>
                    <a href="{% url 'music:software' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Software
                    </a>
                </li>
                <li>
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Index
                    </a>
                </li>
            </ul>
        </div>

        <div class="divA"></div>
        <div class="divB"></div>​

{##}
{#       <div class="sub-nav full" id="sub-nav">#}
{#        <ul class="nav stuff-nav">#}
{#        <li><a href="https://uncrate.com/magazine/">Magazine</a></li>#}
{#        </ul>#}
{#      </div>#}

        <div class="divB"></div>​

    </div>

</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }}<br> <small>{{ album.genre }}</small></h1>
                    <h2> by {{ album.artist }}</h2><br>

            <a href="{% url 'music:album-update' album.id %}" class="btn btn-primary btn-sm" role="button">Update Details</a>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="#">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="#######">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="#" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/detail2.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-2">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }}<br> <small>{{ album.genre }}</small></h1>
                    <h2> by {{ album.artist }}</h2><br>

            <a href="{% url 'music:album-update' album.id %}" class="btn btn-primary btn-sm" role="button">Update Details</a>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="#">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="#######">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="#" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3"><img src="/media/1477621089391.jpg"></h1>
    <p class="lead">
    <a class="btn btn-toolbar btn-lg" href="#" role="button">Author/Source</a>
    </p>

    <h3>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.
    It uses utility classes for typography and spacing to space content out within the larger container.</h3>

    <p class="lead">
    <a class="btn btn-toolbar btn-lg" href="#" role="button">Call To Action</a>
    </p>
  </div>
</div>



    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3></h3>
        </div>
            {% if all_albums %}
                {% for album in all_albums %}
                <div class="col-md-6">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
{#   example of dynamic href       <h5 href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">{{ album.******}}</h5>#}
                            <a>{{ album.genre }}</a>
                            <div><a href="{% url 'music:detail' album.id %}" class="btn btn-toolbar btn-sm" role="button">{{ album.artist }}</a></div>

                            <h3>{{ album.album_title }}</h3>


                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="#">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

{% endblock %}

music/templates/music/mind.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}




<!-- Albums -->
    <div class="row">
        <div class="col-sm-12">

        </div>
            {% if all_albums %}
                {% for album in all_albums %}
                <div class="col-md-6">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h5>{{ album.genre }}</h5>
                            <h3>{{ album.album_title }}</h3>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="#">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
</div>




{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

music/templates/music/software.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}




<!-- Albums -->
    <div class="row">
        <div class="col-sm-12">

        </div>
            {% if all_albums %}
                {% for album in all_albums %}
                <div class="col-md-6">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h5>{{ album.genre }}</h5>
                            <h3>{{ album.album_title }}</h3>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="#">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
</div>




{% endblock %}

music/templates/music/travel.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}




<!-- Albums -->
    <div class="row">
        <div class="col-sm-12">

        </div>
            {% if all_albums %}
                {% for album in all_albums %}
                <div class="col-md-6">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h5>{{ album.genre }}</h5>
                            <h3>{{ album.album_title }}</h3>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="#">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
</div>




{% endblock %}

music/templates/music/uncrateindex.html
<div class="wrapper navigation-wrapper">
    <div class="navigation grid">
      <div class="main-nav full" id="main-nav">
        <ul class="nav">
          <li><a href="https://uncrate.com/gear/">Gear</a></li>
          <li><a href="https://uncrate.com/style/">Style</a></li>
          <li><a href="https://uncrate.com/cars/">Cars</a></li>
          <li><a href="https://uncrate.com/tech/">Tech</a></li>
          <li><a href="https://uncrate.com/shelter/">Shelter</a></li>
          <li><a href="https://uncrate.com/vices/">Vices</a></li>
          <li><a href="https://uncrate.com/body/">Body</a></li>
          <li><a href="https://uncrate.com/etc/">Etc</a></li>
          <li><a href="https://uncrate.com/tv/">Videos</a></li>
        </ul>
      </div>
      <div class="sub-nav full" id="sub-nav">
        <ul class="nav stuff-nav">
        <li><a href="https://uncrate.com/magazine/">Magazine</a></li>
        <li><a href="https://uncrate.com/enlist/">Enlist</a></li>
        <li><a href="https://instagram.com/uncrate" target="_blank">Instacrate</a></li>
        <li><a href="https://uncrate.com/about/stash/" id="stash-nav">Members</a></li>
        </ul>
      </div>
    </div>
  </div>